---
title: "open-neurocode"
format: 
  html:
    page-layout: full
---

This website lists code and data repositories for publications of the [Max Planck Reseach Group NeuroCode](https://www.mpib-berlin.mpg.de/research/research-groups/mprg-neurocode) at the [Max Planck Institute for Human Development, Berlin](https://www.mpib-berlin.mpg.de/en) (sorted by year and author).
The source repository can be found [on GitHub](https://github.com/lnnrtwttkhn/open-neurocode).


```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE
)
library(magrittr)
```

```{r}
data_path = Sys.glob(here::here("data", "data.csv"))
data = data.table::rbindlist(lapply(data_path, data.table::fread))
data_show = data %>%
  .[, title := sprintf("[%s](%s)", title, doi)] %>%
  .[grepl( "github", repo), repo := sprintf("[GitHub](%s)", repo)] %>%
  .[grepl( "osf", repo), repo := sprintf("[OSF](%s)", repo)] %>%
  .[, c("authors", "year", "title", "journal", "repo")] %>%
  data.table::setorder(., -year, authors)
```

```{r}
knitr::kable(data_show, "markdown")
```


